"""src/msr2025/B_Empirical_Study/lib/constants.py

Defines shared constants for the empirical study phase.

Includes:
- Time constants (e.g., one day in milliseconds)
- File paths to preprocessed data for analysis
"""

from pathlib import Path

# Number of milliseconds in one day
ONE_DAY = 24 * 60 * 60 * 1000

# Path to the data file generated by the data preparation and extraction step
SOURCE_FILE_PATH = Path("output/A_Data_Preparation_and_Extraction/data_updates.json")
